#!/bin/sh -e

if [ ! -d data ] ; then mkdir data ; fi
if [ ! -d plot ] ; then mkdir plot ; fi

echo "Calculating female subjects...\n"
./calculate_volumes FemaleSubjects.csv data > female.csv

echo "Calculating male subjects...\n"
./calculate_volumes MaleSubjects.csv data > male.csv

echo "Running analysis...\n"
Rscript repronim_challenge.R

echo "\n"
cat results.txt

exit 0
 
# eof
