#!/bin/sh -e

progname=`basename $0`

if [ $# -ne 1 ]
then
    echo "usage: $progname <nifti file>"
    echo "calculates the brain volume for an image"
    exit 1
fi

fname="$1"
std_fname=`echo "$fname" | sed 's/.nii$/_std.nii/'`
brain_fname=`echo "$fname" | sed 's/.nii$/_std_brain.nii/'`

fslreorient2std "$1" "$std_fname"
bet "$std_fname" "$brain_fname"
fslstats "$brain_fname" -V | awk '{print $2}'

exit 0

# eof
